// Code generated by hack/codegen-version.sh. DO NOT EDIT.
package version

import "time"

const (
	dateFormat string = time.RFC1123Z

	// Git commit (e.g. 1b4716ab84903b2e477135a3dc5afdb07f685cb7)
	GitCommit string = "0376b3b5889599ba203a59642c5fca3f7a435f34"

	// Version contains a (potentially) human-readable version
	// For example 1.1.0 or 1b4716ab84903b2e477135a3dc5afdb07f685cb7
	Version string = "0376b3b5889599ba203a59642c5fca3f7a435f34"

	// gitDate is a date in RFC1123Z format
	gitDate string = "Wed, 25 Jul 2018 11:38:53 +0200"
)

var (
	GitDate time.Time
)

func init() {

	d, err := time.Parse(dateFormat, gitDate)
	if err != nil {
		panic(err)
	}
	GitDate = d
}
